[package]
name = "stn"
description = "A command line tool for managing Taiko nodes."
license = "MIT"
version = "0.1.21"
edition = "2021"
repository = "https://github.com/d1onys1us/stn"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
