[package]
name = "stn"
description.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
ethers = { version = "2.0", features = ["rustls", "ws"] }
reqwest = { version = "0.11", features = ["json", "tokio-rustls"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
