[workspace]
members = [
    "apps/kittynode-cli",
    "apps/kittynode-gui/kittynode-tauri",
    "crates/*",
]
resolver = "2"

[workspace.package]
description = "A tool for managing decentralized node infrastructure."
license = "MIT"
edition = "2021"
repository = "https://github.com/kittynode/kittynode"
readme = "README.md"
