[workspace]
members = [
    "crates/kittynode-cli",
    "crates/kittynode-core",
    "crates/kittynode-tauri",
]
resolver = "2"

[workspace.package]
description = "A tool for managing decentralized node infrastructure."
license = "MIT"
version = "0.4.0"
edition = "2021"
repository = "https://github.com/kittynode/kittynode"
readme = "README.md"
