[workspace]
changelog_config = "cliff.toml"
changelog_update = true
dependencies_update = true
git_tag_enable = true
git_release_enable = false
pr_labels = ["release"]
allow_dirty = false
publish_allow_dirty = false
semver_check = false

[[package]]
name = "kittynode"
changelog_include = ["kittynode_core", "kittynode_gui"]
changelog_path = "./CHANGELOG.md"

[[package]]
name = "kittynode_core"
changelog_update = false

[[package]]
name = "kittynode_gui"
changelog_update = false
