[package]
name = "kittynode-web"
version = "0.1.0"
description.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
axum = "0.8.4"
tokio = { version = "1.45.0", features = ["macros", "rt-multi-thread"] }
kittynode-core = { version = "0.4.0", path = "../core" }
tracing-subscriber = "0.3.20"
