[package]
description.workspace = true
edition.workspace = true
license.workspace = true
name = "kittynode-tauri"
publish = false
readme.workspace = true
repository.workspace = true
version = "0.1.0"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "kittynode_tauri_lib"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
eyre = { version = "0.6", default-features = false, features = [
    "auto-install",
    "track-caller",
] }
kittynode-core = { version = "0", path = "../../../crates/kittynode-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = ["devtools"] }
tauri-plugin-dialog = "2"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[dev-dependencies]
tauri-cli = "2.0.3"
