name: CI - JavaScript

on:
  push:
    paths:
      - docs/**
      - packages/gui/*
      - packages/gui/src/**

jobs:
  format-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Format and lint
        run: bun --elide-lines=0 -F docs -F gui format-lint

      - name: Svelte check
        run: bun --elide-lines=0 -F gui check
