name: CI - Rust

on:
  push:
    paths:
      - packages/cli/**
      - packages/core/**
      - packages/gui/src-tauri/**
      - packages/web/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Create dist directory for tauri dev build (workaround)
        run: mkdir -p ./packages/gui/build

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          # default: "v0-rust"; increment to reset cache
          prefix-key: v1-rust

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        if: github.actor != 'dependabot[bot]'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true

  format-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Create dist directory for tauri dev build (workaround)
        run: mkdir -p ./packages/gui/build

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          # default: "v0-rust"; increment to reset cache
          prefix-key: v1-rust

      - name: Check code formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
