name: Rust Build and Release

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Rust and Cargo
        run: |
          if ! rustc --version &> /dev/null; then
            echo "Rust is not installed"
            exit 1
          fi
          if ! cargo --version &> /dev/null; then
            echo "Cargo is not installed"
            exit 1
          fi

      - name: Build Rust binary
        run: cargo build --release
        working-directory: ./stn # Specify the working directory where Cargo.toml is located

      - name: Create Release Directory
        run: mkdir -p release

      - name: Copy Binary to Release Directory
        run: cp stn/target/release/stn release/ # Use the binary name "stn"

      - name: Upload Release as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: stn # Name of the artifact
          path: release/
