name: Release GUI

on:
  workflow_dispatch:
  push:
    tags:
      - gui.canary.*

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          # - platform: "ubuntu-22.04"
          #   args: ""
          # - platform: "windows-latest"
          #   args: ""
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          # default: "v0-rust"; increment to reset cache
          prefix-key: v1-rust

      - name: Mask sensitive values
        run: |
          echo "::add-mask::${{ secrets.APPLE_CERTIFICATE }}"
          echo "::add-mask::${{ secrets.APPLE_CERTIFICATE_KEY_ID }}"
          echo "::add-mask::${{ secrets.APPLE_CERTIFICATE_PASSWORD }}"
          echo "::add-mask::${{ secrets.APPLE_DEVELOPER_ID }}"
          echo "::add-mask::${{ secrets.APPLE_ID }}"
          echo "::add-mask::${{ secrets.APPLE_PASSWORD }}"
          echo "::add-mask::${{ secrets.APPLE_TEAM_ID }}"

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          draft: true

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          releaseId: ${{ steps.create_release.outputs.id }}
          tagName: ${{ github.ref_name }}
          projectPath: "packages/gui/src-tauri"
          args: ${{ matrix.args }}
          includeUpdaterJson: true
