name: Release app

on:
  workflow_dispatch:
  push:
    tags:
      - kittynode-app@*

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            args: --target aarch64-apple-darwin
          - platform: ubuntu-22.04
            args: ""
          - platform: windows-latest
            args: ""
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Verify version match
        shell: bash
        run: |
          TAG_VERSION=$(echo "${{ github.ref_name }}" | sed 's/^kittynode-app@\([0-9.]*\).*/\1/')
          CARGO_VERSION=$(grep '^version = ' packages/app/src-tauri/Cargo.toml | cut -d'"' -f2)

          if [ "$TAG_VERSION" != "$CARGO_VERSION" ]; then
            echo "Version mismatch: Tag version '$TAG_VERSION' does not match Cargo.toml version '$CARGO_VERSION'"
            exit 1
          fi

          echo "Version check passed: $TAG_VERSION"

      - name: Install system dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Mask sensitive values
        run: |
          echo "::add-mask::${{ secrets.APPLE_CERTIFICATE }}"
          echo "::add-mask::${{ secrets.APPLE_CERTIFICATE_KEY_ID }}"
          echo "::add-mask::${{ secrets.APPLE_CERTIFICATE_PASSWORD }}"
          echo "::add-mask::${{ secrets.APPLE_DEVELOPER_ID }}"
          echo "::add-mask::${{ secrets.APPLE_ID }}"
          echo "::add-mask::${{ secrets.APPLE_PASSWORD }}"
          echo "::add-mask::${{ secrets.APPLE_TEAM_ID }}"

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true

      - name: Build the app
        uses: tauri-apps/tauri-action@v0.5.23
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          releaseId: ${{ steps.create_release.outputs.id }}
          tagName: ${{ github.ref_name }}
          projectPath: packages/app/src-tauri
          args: ${{ matrix.args }}
          includeUpdaterJson: true

  publish-release:
    needs: publish-tauri
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          draft: false

  update-website-version:
    needs: publish-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          ref: main
          # Use GITHUB_TOKEN for the checkout since verified-bot-commit will handle the push
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version file
        id: update_version
        run: |
          VERSION="${{ github.ref_name }}" && VERSION="${VERSION#kittynode-app@}"
          printf '{\n  "version": "%s",\n  "date": "%s"\n}\n' "$VERSION" "$(date +"%B %-d, %Y")" > website/src/lib/release.json
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Commit changes with verified signature
        uses: iarekylew00t/verified-bot-commit@v2
        with:
          token: ${{ secrets.RELEASE_BOT_PAT }}  # Use PAT to bypass branch protection
          message: Update website version to ${{ steps.update_version.outputs.version }}
          files: |
            website/src/lib/release.json
