name: Another release job

on:
  push:
    tags:
      - "v*" # Trigger on tag push that matches v* (e.g., v1.0.0)

permissions:
  contents: write # This line gives the GITHUB_TOKEN permission to create releases

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          # - release_for: FreeBSD-x86_64
          #   os: ubuntu-20.04
          #   target: x86_64-unknown-freebsd
          #   bin: stn
          #   name: stn-FreeBSD-x86_64.tar.gz
          #   command: build

          # - release_for: Windows-x86_64
          #   os: windows-latest
          #   target: x86_64-pc-windows-msvc
          #   bin: stn.exe
          #   name: stn-Windows-x86_64.zip
          #   command: build

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: stn
            name: stn-Darwin-x86_64.tar.gz
            command: build

          - release_for: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: stn
            name: stn-Darwin-aarch64.tar.gz
            command: build

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Create tarball
        run: |
          cd ${{ github.workspace }}/target
          tar -czvf ${{ matrix.platform.name }} ./${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}

      - name: Create Release and Upload Binary
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/target/${{ matrix.platform.name }}
          draft: false # Set to true if you want to create a draft release
          prerelease: false # Set to true if you want to create a prerelease
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: "Description and changelog for the release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Provided by Actions, no need to create a token
