name: Another release job

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: stn
            name: stn-Darwin-x86_64.tar.gz
            command: build
          - release_for: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: stn
            name: stn-Darwin-aarch64.tar.gz
            command: build
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Create tarball
        run: |
          cd ${{ github.workspace }}/target
          tar -czvf ${{ matrix.platform.name }} ./${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}

      - name: Upload Release as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.name }}
          path: ${{ github.workspace }}/target/${{ matrix.platform.name }}

  create-release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download all assets
        uses: actions/download-artifact@v2

      - name: Create Release and Upload Binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/stn-Darwin-x86_64.tar.gz
            ${{ github.workspace }}/stn-Darwin-aarch64.tar.gz
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Description and changelog for the release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
